name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the initial repository (Repo A)
      - name: Checkout repository A
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Clone the destination repository (Repo B, y2j)
      - name: Clone Repo B (y2j)
        run: |
          git clone https://${{ secrets.PAT }}@github.com/${{ env.ORG_NAME }}/y2j.git
        env:
          ORG_NAME: yashbek

      # Run your build script inside Repo B
      - name: Run build script in Repo B
        run: |
          BIN="/usr/local/bin" && \
          VERSION="1.37.0" && \
          curl -sSL \
          "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" \
          -o "${BIN}/buf" && \
          chmod +x "${BIN}/buf"
          cd y2j
          git submodule init
          git -c http.extraheader="AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.PAT }} | base64)" submodule update --recursive --remote
          ./build.sh

      # Commit and push changes back to Repo B
      - name: Commit and Push changes to Repo B
        run: |
          cd y2j
          git config --global user.email "yazbek0890@gmail.com"
          git config --global user.name "yashbek"
          git add -A
          git commit -m "Automated commit from GitHub Actions"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
