name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Clone y2j
      - name: Clone Repo B (y2j)
        run: |
          git clone https://${{ secrets.PAT }}@github.com/yashbek/y2j.git

      # install buf & build
      - name: Run build script in y2j
        run: |
          BIN="/usr/local/bin" && \
          VERSION="1.37.0" && \
          curl -sSL \
          "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" \
          -o "${BIN}/buf" && \
          chmod +x "${BIN}/buf"
          cd y2j
          git submodule init
          git -c http.extraheader="AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.PAT }} | base64)" submodule update --recursive --remote
          ./build.sh

      # add, commit, and push
      - name: add, commit, and push
        run: |
          cd y2j
          git config --global user.email "yazbek0890@gmail.com"
          git config --global user.name "yashbek"
          git add -A
          git commit -m "bump"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      # Clone y2m
      - name: Clone Repo B (y2m)
        run: |
          git clone https://${{ secrets.PAT }}@github.com/yashbek/y2m.git

      # install buf & build
      - name: Run build script in y2m
        run: |
          BIN="/usr/local/bin" && \
          VERSION="1.37.0" && \
          curl -sSL \
          "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" \
          -o "${BIN}/buf" && \
          chmod +x "${BIN}/buf"
          cd y2m
          git submodule init
          git -c http.extraheader="AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.PAT }} | base64)" submodule update --recursive --remote
          ./build.sh

      # add, commit, and push
      - name: add, commit, and push
        run: |
          cd y2m
          git config --global user.email "yazbek0890@gmail.com"
          git config --global user.name "yashbek"
          git add -A
          git commit -m "bump"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
